#!/usr/bin/env python3
"""Run restored historical snapshots through the production-like replay pipeline.

Normal usage is intentionally simple:

    python tests/replays/replay_unprocessed.py

If the database contains snapshots from more than one day, specify only the day:

    python tests/replays/replay_unprocessed.py --day 2026-08-03

Stage switches are source configuration below rather than separate CLI flags.
The normal/default run is the complete downstream pipeline. Snapshot creation is
always a no-op because this runner assumes snapshots have already been restored
or generated by the existing snapshot replay utility.
"""
from __future__ import annotations

import argparse
from datetime import date, time as dtime
import logging
import os
import sys
from typing import Optional, Sequence

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from logconfig import setup_logging
from tests.replays.replay_pipeline import (
    ReplayPipelineConfig,
    ReplayStages,
    resolve_trading_day,
    run_replay_pipeline,
)

# =============================================================================
# NORMAL REPLAY CONFIGURATION
# =============================================================================

REPLAY_START_TIME = dtime(9, 18)
REPLAY_END_TIME = dtime(15, 15)

# Keep this explicit for the current one-user research workflow. Set to None to
# use the same eligible-user discovery as production TradeGenerator/Executor.
REPLAY_USERID: Optional[str] = "DR1812"

# One place to suppress a stage for diagnostics without multiplying CLI flags.
# Snapshot generation remains a no-op by design in this runner.
STAGES = ReplayStages(
    snapshots=False,
    signals=True,
    trade_generator=True,
    executor=True,
    monitor=True,
)

LOG_FILE = "reports/replay_unprocessed.log"
logger = logging.getLogger(__name__)


def _parse_day(value: Optional[str]) -> Optional[date]:
    text = str(value or "").strip()
    return date.fromisoformat(text) if text else None


def _args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Replay restored snapshots through the production-like pipeline."
    )
    parser.add_argument(
        "--day",
        default=None,
        help="Trading day YYYY-MM-DD. Omit when the DB contains one snapshot day.",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _args(argv)
    setup_logging(log_file=LOG_FILE)

    try:
        trading_day = resolve_trading_day(_parse_day(args.day))
        result = run_replay_pipeline(
            ReplayPipelineConfig(
                trading_day=trading_day,
                start_time=REPLAY_START_TIME,
                end_time=REPLAY_END_TIME,
                userid=REPLAY_USERID,
                stages=STAGES,
            )
        )
        return 1 if result.had_errors else 0
    except KeyboardInterrupt:
        logger.info("Replay interrupted; successfully processed snapshots remain marked")
        return 130
    except Exception:
        logger.exception("replay_unprocessed failed during startup/preflight")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
